# Generated by Django 4.2.1 on 2023-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('content_title', models.CharField()),
                ('content_url', models.URLField()),
                ('content_description', models.TextField()),
            ],
        ),
    ]
