# Generated by Django 4.2.1 on 2023-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_normal',
            field=models.BooleanField(default=None),
        ),
    ]
