# Generated by Django 4.2.1 on 2023-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment_is_normal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_normal',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
