# Generated by Django 4.2.1 on 2023-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_comment_is_normal_comment_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
