# Generated by Django 4.2.1 on 2023-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=125)),
                ('django_email', models.EmailField(max_length=254)),
                ('about_us', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('vk_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
