# Generated by Django 4.2.1 on 2023-07-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='wk_link',
            new_name='vk_link',
        ),
    ]
