#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL PgPool to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL PgPool is available'

exec "$@"