# Generated by Django 4.2.1 on 2023-07-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
