# Generated by Django 4.2.1 on 2023-06-08 10:36

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug_link', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['name'])),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_title', models.CharField(max_length=255)),
                ('orig_title', models.CharField(max_length=255)),
                ('released', models.CharField(blank=True, max_length=15, null=True)),
                ('iframe_src', models.CharField(max_length=255, unique=True)),
                ('slug_link', autoslug.fields.AutoSlugField(editable=False, populate_from='orig_title', unique_with=['orig_title'])),
                ('genre', models.ManyToManyField(blank=True, related_name='ganre', to='movies.genre')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Previews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.movie')),
            ],
        ),
    ]
